### ISSUE TITLE
No interface method stream()

### ISSUE THREAD

**Issue by yosoycody** [sputnikdev/bluetooth-gatt-parser#12]
On on older Android device running Android 6, I'm seeing the following crash:
```
java.lang.NoSuchMethodError: No interface method stream()Ljava/util/stream/Stream; in class Ljava/util/Set; or its super classes (declaration of 'java.util.Set' appears in /system/framework/core-libart.jar)
        at org.sputnikdev.bluetooth.gattparser.spec.BluetoothGattSpecificationReader.loadExtensionsFromCatalogResources(BluetoothGattSpecificationReader.java:263)
        at org.sputnikdev.bluetooth.gattparser.spec.BluetoothGattSpecificationReader.<init>(BluetoothGattSpecificationReader.java:92)
        at org.sputnikdev.bluetooth.gattparser.BluetoothGattParserFactory.getSpecificationReader(BluetoothGattParserFactory.java:59)
        at org.sputnikdev.bluetooth.gattparser.BluetoothGattParserFactory.getDefault(BluetoothGattParserFactory.java:74)
```

**Comment by mimoccc** [comment]
Thats because stream() works only on higher java or sdk version.
